// Language names and tags from WinUI Gallery Helpers/Language/LanguageList.cs (MIT).
package io.github.composefluent.winrt.gallery

internal val galleryLanguages = listOf(
    "English" to "en",
    "Arabic" to "ar",
    "Afrikaans" to "af",
    "Albanian" to "sq",
    "Amharic" to "am",
    "Armenian" to "hy",
    "Assamese" to "as",
    "Azerbaijani" to "az",
    "Basque " to "eu",
    "Belarusian" to "be",
    "Bangla" to "bn",
    "Bosnian" to "bs",
    "Bulgarian" to "bg",
    "Catalan" to "ca",
    "Chinese (Simplified)" to "zh",
    "Croatian" to "hr",
    "Czech" to "cs",
    "Danish" to "da",
    "Dari" to "prs",
    "Dutch" to "nl",
    "Estonian" to "et",
    "Filipino" to "fil",
    "Finnish" to "fi",
    "French " to "fr",
    "Galician" to "gl",
    "Georgian" to "ka",
    "German" to "de",
    "Greek" to "el",
    "Gujarati" to "gu",
    "Hausa" to "ha",
    "Hebrew" to "he",
    "Hindi" to "hi",
    "Hungarian" to "hu",
    "Icelandic" to "is",
    "Indonesian" to "id",
    "Irish" to "ga",
    "isiXhosa" to "xh",
    "isiZulu" to "zu",
    "Italian" to "it",
    "Japanese " to "ja",
    "Kannada" to "kn",
    "Kazakh" to "kk",
    "Khmer" to "km",
    "Kinyarwanda" to "rw",
    "KiSwahili" to "sw",
    "Konkani" to "kok",
    "Korean" to "ko",
    "Lao" to "lo",
    "Latvian" to "lv",
    "Lithuanian" to "lt",
    "Luxembourgish" to "lb",
    "Macedonian" to "mk",
    "Malay" to "ms",
    "Malayalam" to "ml",
    "Maltese" to "mt",
    "Maori " to "mi",
    "Marathi" to "mr",
    "Nepali" to "ne",
    "Norwegian" to "nb",
    "Odia" to "or",
    "Persian" to "fa",
    "Polish" to "pl",
    "Portuguese" to "pt",
    "Punjabi" to "pa",
    "Quechua" to "quz",
    "Romanian" to "ro",
    "Russian" to "ru",
    "Serbian (Latin)" to "sr",
    "Sesotho sa Leboa" to "nso",
    "Setswana" to "tn",
    "Sinhala" to "si",
    "Slovak " to "sk",
    "Slovenian" to "sl",
    "Spanish" to "es",
    "Swedish" to "sv",
    "Tamil" to "ta",
    "Telugu" to "te",
    "Thai" to "th",
    "Tigrinya" to "ti",
    "Turkish" to "tr",
    "Ukrainian" to "uk",
    "Urdu" to "ur",
    "Uzbek (Latin)" to "uz",
    "Vietnamese" to "vi",
    "Welsh" to "cy",
    "Wolof" to "wo",
)
