package io.github.composefluent.winrt.gallery.styles

import io.github.composefluent.winrt.gallery.*
import microsoft.ui.xaml.controls.*
import microsoft.ui.xaml.controls.animatedvisuals.*

@GalleryPage(route = "AnimatedIcon", title = "AnimatedIcon", group = "Styles", order = 1)
internal fun animatedIconPage() = ExamplePage {
    val names = listOf("AnimatedBackVisualSource", "AnimatedChevronDownSmallVisualSource", "AnimatedChevronRightDownSmallVisualSource", "AnimatedChevronUpDownSmallVisualSource", "AnimatedFindVisualSource", "AnimatedGlobalNavigationButtonVisualSource", "AnimatedSettingsVisualSource")
    fun source(index: Int): IAnimatedVisualSource2 = when (index) {
        0 -> AnimatedBackVisualSource()
        1 -> AnimatedChevronDownSmallVisualSource()
        2 -> AnimatedChevronRightDownSmallVisualSource()
        3 -> AnimatedChevronUpDownSmallVisualSource()
        4 -> AnimatedFindVisualSource()
        5 -> AnimatedGlobalNavigationButtonVisualSource()
        else -> AnimatedSettingsVisualSource()
    }
    val icon = AnimatedIcon().apply { this.source = source(4); fallbackIconSource = SymbolIconSource().apply { symbol = Symbol.Find } }

    example("Adding an AnimatedIcon to a Button.", animatedIconButtonSample(icon), select("Kind", names, 4) { icon.source = source(it) })

    example("Adding an AnimatedIcon to a NavigationView.", animatedIconNavigationViewSample())


}

@GallerySample(route = "AnimatedIcon", title = "Adding an AnimatedIcon to a Button.")
internal fun animatedIconButtonSample(icon: AnimatedIcon) = stack {
    children.add(TextBlock().apply { this.text = "The following example is a button that the user clicks to load a search experience. The AnimatedIcon consumes the animation created using Adobe AfterEffects and translated into Microsoft.UI.Composition objects using Lottie-Windows. For guidance on how to properly structure your animation file see the AnimatedIcon Guidance page."; this.fontSize = 14.0; this.textWrapping = microsoft.ui.xaml.TextWrapping.Wrap })
    children.add(Button().apply {
        width = 75.0; content = icon; named(this, "AnimatedIcon Example")
        pointerEntered.add { _, _ -> AnimatedIcon.setState(icon, "PointerOver") }
        pointerExited.add { _, _ -> AnimatedIcon.setState(icon, "Normal") }
    })
}

@GallerySample(route = "AnimatedIcon", title = "Adding an AnimatedIcon to a NavigationView.")
internal fun animatedIconNavigationViewSample() = stack {
    children.add(TextBlock().apply { this.text = "If you set an AnimatedIcon as the value of the Icon property, the NavigationViewItem will set the states of the AnimatedIcon for you, according to the states of the control. For guidance on how to properly structure your animation file see the AnimatedIcon Guidance page.\n\nFor this example, this sets a custom animation GameSettingsIcon that was generated by the LottieGen tool."; this.fontSize = 14.0; this.textWrapping = microsoft.ui.xaml.TextWrapping.Wrap })
    children.add(NavigationView().apply {
        isSettingsVisible = false
        menuItems.add(NavigationViewItem().apply {
            content = "Game Settings"
            this.icon = AnimatedIcon().apply {
                this.source = AnimatedSettingsVisualSource()
                fallbackIconSource = FontIconSource().apply { glyph = "\uE713" }
            }
        })
    })
}
